### ISSUE TITLE
Missing Packages when trying to build Library.

### ISSUE THREAD

**Issue by sgtfrankieboy** [aspnet/DataCommon.SQLite#65]
When trying to run `build initialize` I get the following error:

```
Microsoft (R) Build Engine version 12.0.31010.0
[Microsoft .NET Framework, version 4.0.30319.0]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12-2-2015 22:00:42.
Project "F:\Projects\Git\aspnet\DataCommon.SQLite\src\Microsoft.Data.SQLite\Microsoft.Data.SQLite.csproj" on node 1 (WritePackageReferences
 target(s)).
F:\Projects\Git\aspnet\DataCommon.SQLite\tools\DataCommon.SQLite.targets(96,5): error : No packages found. [F:\Projects\Git\aspnet\DataComm
on.SQLite\src\Microsoft.Data.SQLite\Microsoft.Data.SQLite.csproj]
Done Building Project "F:\Projects\Git\aspnet\DataCommon.SQLite\src\Microsoft.Data.SQLite\Microsoft.Data.SQLite.csproj" (WritePackageRefere
nces target(s)) -- FAILED.


Build FAILED.

"F:\Projects\Git\aspnet\DataCommon.SQLite\src\Microsoft.Data.SQLite\Microsoft.Data.SQLite.csproj" (WritePackageReferences target) (1) ->
(WritePackageReferences target) ->
  F:\Projects\Git\aspnet\DataCommon.SQLite\tools\DataCommon.SQLite.targets(96,5): error : No packages found. [F:\Projects\Git\aspnet\DataCo
mmon.SQLite\src\Microsoft.Data.SQLite\Microsoft.Data.SQLite.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.23
warn: Exit code 1 from C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe
verbose: Stack trace:
   at View0fb233d2bff84d9ebce2475427c2d645.<RenderViewLevel0>b__66() in c:\Users\Frank\AppData\Local\Temp\a00af3b1699a4e8aaaebcec4d1f538a5-1.cs:line 9149
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View0fb233d2bff84d9ebce2475427c2d645.<RenderViewLevel0>b__43() in c:\Users\Frank\AppData\Local\Temp\a00af3b1699a4e8aaaebcec4d1f538a5-1.cs:line 1283
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

I also had to change `Xunit.KRuntime` in project.json of the test project to `xunit.runner.kre`.

Side Note: Where is the DataCommon repository? Link in the Read me is dead.

**Comment by bricelam** [comment]
This repository has fallen into disrepair while we [focus on other priorities](http://blogs.msdn.com/b/adonet/archive/2014/12/02/ef7-priorities-focus-and-initial-release.aspx).

You might be able to get it building by updating the `project.json` file to reference version `4.0.0-beta-*` of `System.Data.Common`. We switched to using the [dotnet/corefx](https://github.com/dotnet/corefx) version which hasn't been [added to their repository yet](http://blogs.msdn.com/b/dotnet/archive/2015/01/28/net-core-open-source-update.aspx).
